### ISSUE TITLE
[TASK]: Remove the `Overlay` from the App.vue

### ISSUE THREAD

**Issue by YohannParis** [DARPA-ASKEM/TERArium#112]
**Is your feature request related to a problem? Please describe.**
- Before opening the _Data Explorer_ an overlay, used as a loading screen, is displayed.

**Describe the solution you'd like**
- Remove the `Overlay` component for now.

**Improvement going forward**

- We should move toward a [_Skeleton screens_](https://www.lukew.com/ff/entry.asp?1797) approach. 
- Making sure that each component waiting for data or information as an empty state design.
- @bencodrington and @pascaleproulx: if I can get your opinion on the matter?

**Comment by amostafa-uncharted** [comment]
We could combine a status indicator with the default/empty state design. 
Take the data explorer as an example, when the page first load, the default state design may be something like an empty list which will be populated after a few seconds. Without having some status indicator or an appropriate message, the user may feel that no data is available which is not true because the data is still being loaded from the server!

**Comment by bencodrington** [comment]
Strongly agree with the skeleton screens approach. Apart from the cognitive psychology benefits, this also lets the user continue to interact with the application (start filtering, navigate to another page, etc.) while the heavy content loads.

I'm working on the ModelRenderer component now, and a faint animation shows that it's loading without drawing attention to the missing content, which hopefully addresses your concern @amostafa-uncharted.

https://user-images.githubusercontent.com/16928557/201442866-501adfa1-63c7-48d3-b9ea-8cbc522d181d.mov
