### ISSUE TITLE
[BUG]: Multi-selection in one facet yields unexpected results

### ISSUE THREAD

**Issue by pascaleproulx** [DARPA-ASKEM/terarium#1230]
**Describe the bug**
Multi-selection in one facets shows no results even in cases where there should be some.

**To Reproduce**
1. Search for 'covid'
2. Click on github facet first repo
3. See screenshot: 438 results, and of those, 16 also have the next repo...
4. Click on the second repo: instead of showing the 16, it shows nothing.

<img width="560" alt="image" src="https://github.com/DARPA-ASKEM/Terarium/assets/42645294/bd851af1-0797-4b4e-b9fd-cb9374c17706">

**Expected behavior**
From World Modelers: selecting multiple members from one facet should do an 'OR'. Selecting across facets should do an 'AND'. Could also check with @chris-dickson what should be expected based on what was done for TellFinder.

**Comment by chris-dickson** [comment]
That's correct @pascaleproulx.  For example, selecting two publication years and the first github repo should result in the query:
` ( year:2002 || year:2001 ) && (github:CSSEGISandData/COVID-19)`

The complications arise when you have to decide what to show in each facet. Because we immediately requery upon clicking a facet, it's desireable to not show values that could lead to zero results when combined. For example, upon filtering to the year 2022 we should only show values in other facet groups that have values in the year 2022, otherwise filtering further would lead to zero results.  But what should be displayed in the year facet in this case? If we show the remaining possible year values it leads to a very non-intuitive situation when display the subcounts (eg/ `n / total`) where in order to get values from another year the user must click on a facet value that says 0.
