### ISSUE TITLE
[TASK]: Refactor the model page

### ISSUE THREAD

**Issue by YohannParis** [DARPA-ASKEM/Terarium#1328]
**Describe the task**
The model page needs to be cleaned up and re-organized.

**Goal**
Being able to understand what's happening

**Comment by mwdchang** [comment]
In discussion with @YohannParis I was proposing something like this ... where xyz denotes the framwork type, e.g. tera-model-petri, tera-model-pde ... etc
```
## Proposal for general tera-model-xyz
- tera-model-xyz
 - description/overview
  - enrichment
  - copy model
 - detail (in its own opration according to Pascale)
  - diagrams
  - equations
 - llm/jupyter
```

Right now various components under tera-model are doing their own things, I think we should try to reduce that and use tera-model-xzy as a more central controller. For example the two configuration components are both fetching model-configurations and performing CRUD, which isn't ideal for maintenance. LIkewise equation and diagram are both updating the AMR which makes coordinating things harder than necessary in my opinion.


So
- tera-model-xyz should be try to fetch the data necessary, and to coordinate updates and events
- children components should emit request to tera-model-xyz rather than performing CRUD themselves
- obviously there are some exceptions here e.g. with the Jupyter LLM interface which is effective its own environment.

**Comment by mwdchang** [comment]
<img width="936" alt="image" src="https://github.com/DARPA-ASKEM/Terarium/assets/1220927/d1cb1ed6-c881-46e0-858f-30d5a834d587">


A few dangling discussion points
- Do we want a giant centralized controller to handle all things? or should we delegate where things are independent? 
  - pro: easy to find where to do stuff
  - con: file get get large and harder to maintain, more merge conflicts, harder to find specific functions
- What is the data-passing mechanism that we want to have? 
  - Pass each sub-components exactly what they need.
    - pro: promotes better reuse, e.g. equation component
    - con: much more difficult to do error handling because they may not have enough context to figure things out
 - Pass component the model and let them figure out what they need
   - pro: more unified interface (e.g. pass model to every first level component), has sufficient context to figure out more complicated logic
   - con: potentially passing in more data than needed
