### ISSUE TITLE
Implement joint posterior distribution from PYCIEMSS

### ISSUE THREAD

**Issue by YohannParis** [DARPA-ASKEM/terarium#1640]
CIEMSS produces a joint-distribution object blob - we should investigate ways to use it for analysis. 

Note this is something like a pickled pyro/chirho python object and not something that is JSON serializable.

Technical Tasks:
- [ ] Store data blob in TDS
- [ ] reference data blob back to pyciemss during simulation call
- [ ] separate calibrate/simulate into separate workflow boxes

Research Tasks:
- [ ]  Investigate visualization and analytics of the blobs

**Comment by dgauldie** [comment]
Nelson needs to get an example first

**Comment by liunelson** [comment]
@fivegrant 

Let me know when you get to this issue!

This notebook captures my investigation of this issue:
[https://github.com/liunelson/pyciemss/blob/nl-test/notebook/integration_demo/nliu/review_interfaces.py](https://github.com/liunelson/pyciemss/blob/nl-test/notebook/integration_demo/nliu/review_interfaces.py)

I have mostly finished investigating the blobs:
* the next step probably is to update the existing simulation service to store and run functions over the blobs and serve the result of these functions back to Terarium
* the blobs are the non-serializable (and thus must be stored as a pickle/dill) values that are returned by a PyCIEMSS calibration.
* the two relevant functions are `load_and_calibrate_and_sample_petri_model` and `load_and_calibrate_and_optimize_and_sample_petri_model`
* No change to the inputs of the `load_...` functions is needed to get the blob: the blob is now included by default
* the output of the former is a dict with the keys `data, quantiles, risk, inferred_parameters`
* the values of `data, quantiles, risk` are just Pandas dataframes
* the value of `inferred_parameters` is _the_ blob (with type `pyro.infer.autoguide.guides.AutoGuideList`)
* the blob can be slice-and-diced using the function `get_posterior_density_mesh_petri`which basically takes a user-given high-dimensional mesh (each point = a possible parameter configuration), evaluates the probability for each mesh point, and returns those probability values.
* we might need a service that would allow Terarium to send some custom mesh configuration (a tuple `(lower_bound, upper_bound, num_points)` for every parameter) and get back values over that mesh.
* Alternatively, we can pre-compute some meshes/values over the blob and send those on demand.
* Caution: this mesh and its values can be quite memory intensive since PyCIEMSS accepts only Cartesian meshes and a simple model like SIDARTHE has 16 parameters and its mesh/value array is 16-dimensional with `num_points` along each dimension.
* For the frontend, the result could appear as a plot like this for every pair (or triplet in 3D) of parameters.
![Image](https://github.com/DARPA-ASKEM/Terarium/assets/1030720/fef27ac3-7ee0-4273-a565-b4c44ea5245b)

**Comment by fivegrant** [comment]
confirmed with @liunelson that we can close for now
