### ISSUE TITLE
[BUG]: Incorrect value being used in model-edit

### ISSUE THREAD

**Issue by mwdchang** [DARPA-ASKEM/terarium#3025]
@pascaleproulx reported this:

When using model-edit operator, if we have a model say `A => B => C = D`, 

- If we were to remove the `C => D` template, we should be left with `A => B =C`, this is correct.
- however if we go out, and then go back to the model-edit-operator, the wizard is showing the original input `A => B => C => D` still, as oppose to the new output that had been created in step-1.

**Comment by shawnyama** [comment]
I think the edited state should be maintained once the user reopens the drilldown and saved within `outputs[]`. If the user wants to edit from scratch then we can have a button for that. This would create a new output with the original model so the user could edit from there. This would support the notebook and the wizard to always be in sync.

Maybe options to start editing from a specific output rather than from scratch could be useful as well.

**Comment by pascaleproulx** [comment]
That implies showing the output dropdown in the graphical template view as a start.

**Comment by shawnyama** [comment]
It could be in the header like this, some operators already have it:
![image](https://github.com/DARPA-ASKEM/terarium/assets/28237258/5403e472-9072-47a7-b378-841efe5db66b)

**Comment by YohannParis** [comment]
@pascaleproulx is this still relevant?
