### ISSUE TITLE
[FEAT]: UX Design: Input resource tags for operator drill-down headers

### ISSUE THREAD

**Issue by ngraham76** [DARPA-ASKEM/terarium#3180]
When viewing an operator's drill-down, we need to display resource inputs as tags in the header (in line with the operator's title) so the user knows what resources they are working with in the operator.

**Figma** [link](https://www.figma.com/file/mAGUkTBlT0Yu4L5iGSEcb3/Terarium---Master?type=design&node-id=1%3A51105&mode=design&t=yhWCEvonlOEl8JYb-1).

**Prime Vue tag component** [link](https://primevue.org/tag/).

- Fill: #F7F7F7
- Outline: #E1E1E1, 1px
- Icon / text: #020203
- 16px spacing between tags, operator title and close X button

<img width="759" alt="image" src="https://github.com/DARPA-ASKEM/terarium/assets/141876103/31bec3a4-da21-4b77-9c2e-7f592939b65a">

If an operator has only one input (in this case, a model) then only the one tag would be displayed in the header:
<img width="1197" alt="image" src="https://github.com/DARPA-ASKEM/terarium/assets/141876103/39b8680c-0c2e-42b7-8687-a22b1f3d913f">

Additional resource inputs would display in horizontally aligned tags, filling the space and truncating if the names exceed the allotted space. 
<img width="1166" alt="image" src="https://github.com/DARPA-ASKEM/terarium/assets/141876103/44315aab-41ec-48dd-a5ff-6c5487f96fa8">

<img width="872" alt="image" src="https://github.com/DARPA-ASKEM/terarium/assets/141876103/43f598da-e3ba-426e-b71d-ad95c9a72cd1">

Any file names that exceed the allotted space should be truncated: 
<img width="782" alt="image" src="https://github.com/DARPA-ASKEM/terarium/assets/141876103/23e59e95-a220-4818-8fae-05833c2d75ca">

Let me know if you have any questions, thanks! -Neil

**Comment by YohannParis** [comment]
I'm worried we are trying to put too much information in those drill-down, to the point that they are loosing their simple appearance as an overlay screen.

They represent 80% of the application, and we do not give them the full application visual real estate.

A full page with the Terarium header and footer with a nice breadcrumb/link to represent the hierarchy of where we are in the workflow, with side panels to display inputs/outputs and their related action, would do a clearer job.

I will work on a small mock-up of what I’m thinking to see if it’s worth looking into it.

**Comment by jamiewaese-uncharted** [comment]
I'm not against that... sounds kinda interesting. We're using drilldown modals because they keep you in context a little better than a full screen takeover. I'm not sure how much difference 24px off the sides and top makes... but I'm curious to see what you have in mind for displaying the inputs and outputs. 

Until we make a decision and build that, however, this mini-feature fixes a design fail in our current header. I often find myself working in an operator and forgetting what resource I piped into it. So I have to close it, look at the node, and then reopen it.

I don't agree that this is putting too much information in the drilldown. The name of the thing you're editing, transforming, stratifying, etc. is key information! :)
