### ISSUE TITLE
Updating output metadata should not create a new ouptut

### ISSUE THREAD

**Issue by YohannParis** [DARPA-ASKEM/terarium#4040]
When updating _metadata_ on output of an operator, do not create a new output but update the current one.

- name
- description
- summary id
- source properties (for example for model config parameter value)

[Slack Message](https://unchartedsoftware.slack.com/archives/C03S02YH3D5/p1720042151754959)

**Comment by YohannParis** [comment]
Let's meet with @blanchco and @mwdchang on wednesday to talk about it in detail.

**Comment by mwdchang** [comment]
@YohannParis there are maybe a few different things rolled up in here - can we explicitly define what is the ask here? Because these things may have conflicting interests.

1. Objects with fields that are "editable". We have some notions of objects that can be edited after-the-fact, for example description and source fields in metadata for a model. These are information-only fields and generally speaking have no impact down stream.

2. Updating output-port after the fact. This is generally discouraged because it is easy for things to start going out of sync. For example updating the output would require a mirror-ed update against the linked inputs. More generally speaking the only field that is safe to update is `port.label`.

3. There is an idea of turning an anonymous output object into a "named" object that can be tracked as part of the project's manifest. This idea is not very well defined, in particular because we labelled this as "save as" and it is not entirely clear if the intention is to:
- save object into new instance, as one typically associate with save-as mechanism, or
- change the the object's editable attributes (see point-1) and make the object available in project space

**Comment by dgauldie** [comment]
linked with #4053

**Comment by dgauldie** [comment]
closing since we have created new issues for this task
