### ISSUE TITLE
[FEAT]: Cache Data Transformer output

### ISSUE THREAD

**Issue by YohannParis** [DARPA-ASKEM/terarium#4402]
### Describe

When re-opening a Data Transformer operator, we currently reload the saved Beaker Notebook Session and rerun it. Instead, we should cache the previous run of the Notebook Session and save its outputs (such as dataset previews, charts, code, etc.) into an Artifact asset stored in S3. This way, when the operator is re-opened, the user can see the work that was previously done without needing to reload and re-run the Notebook Session.

#### Example
Login to https://app.staging.terarium.ai using the `qa@test.io` account and go to [this operator](https://app.staging.terarium.ai/projects/94468de1-9f6e-4ebf-9214-9d6d2e7e4981/workflow/c8c89600-0891-472f-b080-74d085ee1c99?operator=0834a35a-9caa-4b29-8fc5-d365d1bb26d3)

**Comment by kbirk** [comment]
So it looks like the image related data that is missing are the `display_data` msg types. The frontend should really just store every message type that it renders in the `data` portion of the NotebookSession, and then when the page reloads, pull those and re-render them as is. The guts of it seems to be `tera-jupyter-chat.vue` 

Currently when the view loads it re-executes everything and then appends the new responses onto the existing notebook session. Ideally if it re-executes it should replace all of the existing data so that the notebook session doesnt grow with each view.
