### ISSUE TITLE
[TASK]: Test Nougat locally

### ISSUE THREAD

**Issue by YohannParis** [DARPA-ASKEM/terarium#4417]
**Describe the task**
* [Meta Nougat ML](https://github.com/facebookresearch/nougat) can extract _LaTeX_ from PNG of a PDF's pages.
* We want to prove that it works well for our use cases

**Task Items**
- [ ] Run the [Docker API image](https://github.com/facebookresearch/nougat/blob/main/docker/README.md) locally
- [ ] Feed [our testing PDFs SIDARTHE and SIDARTHEV](https://drive.google.com/drive/folders/1jSvDlx4LrexjNf0LDvpqLyDZfMxJN72g) and analyse the results with @j2whiting and @YohannParis

**Comment by bigglesandginger** [comment]
# Mac build
Tried building the python code on M1 Mac as torch maybe runs better on Apple Silicon now, but failed with a message about `aiohttp` 

```
aiohttp/_websocket.c:196:12: fatal error: 'longintrepr.h' file not found
```

Maybe it is a wrong version of aiohttp, however, there is no reference to that in the nougat code base.

# Docker build
On the Docker front I have tried to build the CUDA container but it fails due to 

```
102.2 error: torch 2.0.1 is installed but torch<4.0,>=2.1.0 is required by {'lightning'}
```

I have tried changing `setup.py` to limit `lightning` to not its latest, but that doesn't appear to work.  I will try to specify a torch version that `pip` installs as it does not appear to install the latest for "reasons".

**Comment by j2whiting** [comment]
A very simple way to benchmark the model against our data is to generate the Latex, render as a PDF and then compare to the original PDF visually.

<img width="1044" alt="image" src="https://github.com/user-attachments/assets/c2091e77-a76e-49ae-ad0c-007cc031771c">

**Comment by bigglesandginger** [comment]
So, maybe CUDA is great on a Linux machine with a NVidia card, but as that is not what I have or access to (at home I have potential of a Windows box with a much more affordable and equally great AMD graphics card...) and the python code refuses to run on my mac for reasons of wrong chip type and the Docker container fails because Cu118 cannot load torch > 2.0.1 even though all the versions of torch are in the distribution directory, this is non starter software.

**Comment by YohannParis** [comment]
@YohannParis to bug @AndrewjUncharted to get ssh access to the ML box

**Comment by AndrewjUncharted** [comment]
One moment @YohannParis
