### ISSUE TITLE
[BUG]: Terarium becomes completely nonresponsive for 1-2 minutes when editing a sizable model

### ISSUE THREAD

**Issue by liunelson** [DARPA-ASKEM/terarium#4563]
**Describe the bug**
On Staging, I have this model `model_seirhd_effect_vacc2_dose_age.json` and I can upload this model to Terarium with issue. I can also recreate it within Terarium using Stratify Model. However, when I plug it into Edit Model to remove some transitions using the Notebook view (quickly skipping the Wizard spinner), Terarium becomes completely nonresponsive or freezes for 1 or 2 minutes. After, everything is fine though - I can do the edits etc.

[model_seirhd_effect_vacc2_dose_age.json](https://github.com/user-attachments/files/16730553/model_seirhd_effect_vacc2_dose_age.json)

**To Reproduce**
1. Go to ['here'](https://app.staging.terarium.ai/projects/34e7b955-f408-4e8b-be27-9429480ad6aa/workflow/e191aa4b-6f56-4bd5-80bb-f4ee81af9a23)

2. Drag "_ with effects (_ age)" onto the canvas
3. Connect it to a Edit Model operator
4. Click "Edit"
5. Quickly go to the "Notebook" tab
6. Start typing in the LLM field
7. It should freeze up now

**Expected behavior**
DO NOT FREEZE UP

**Comment by mwdchang** [comment]
Part of the problem is in general the model here had been stratified several times with many stratification groups. And then we are basically trying to visualize it in the wizard-view, which means it is very very expensive and can possibly cause the page to become unresponsive. 

Here we are making some 200+ calls to do amr-to-mmt for each template, so it clogs up the network. 
Also we don't have the auto-layout to handle 200+ nodes in the first place.

Probably worth considering is to simply disable the wizard view if there are too many nodes/states/edges in the AMR. Something like: if there are 50+ states do not proceed with the wizard view.
