### ISSUE TITLE
[TRIAGE]: Investigate whether we need to maintain a "transientModelConfig" for model-config outputs

### ISSUE THREAD

**Issue by mwdchang** [DARPA-ASKEM/terarium#4662]
ModelConfiguration operator state is currently defined as

```
export interface ModelConfigOperationState extends BaseState {
  transientModelConfig: ModelConfiguration;
  notebookHistory: NotebookHistory[];
  hasCodeRun: boolean;
  datasetModelConfigTaskId: string;
  documentModelConfigTaskId: string;
}
```

Which is then copied whenever we append an operator output. This data is very heavy, especially `transientModelConfig` which significantly increase the workflow's size and doesn't really like it is being used.

Since output.state is defined as `Partial<ModelConfigOperationState>` we don't need save every piece of operator.state into output.state.

For example in simulate, we are selective in what output.state gets:
```
  emit('append-output', {
    type: SimulateCiemssOperation.outputs[0].type,
    label: nodeOutputLabel(props.node, 'Dataset'),
    value: [datasetResult.id],
    state: {
      currentTimespan: state.currentTimespan,
      numSamples: state.numSamples,
      method: state.method,
      summaryId: summaryResponse?.id,
      forecastId: runId
    },
    isSelected: false
  });
```

See if we can remove `transientModelConfig` from output.state.

**Comment by blanchco** [comment]
Since we are now using the side panel to select model configs, we no longer need `transientModelConfig` to be stored in the output `state`.  We can simply populate `knobs.transientModelConfig` with either the side panel model configuration or `state.transientModelConfig`.  We can apply the same idea to the intervention policy operator as well since it is using the same pattern
