### ISSUE TITLE
[BUG]: Unable to use "Save as" on some model configurations in the `Configure Model` operator

### ISSUE THREAD

**Issue by liunelson** [DARPA-ASKEM/terarium#4676]
**Describe the bug**

Tenzin created several model configurations for the monthly demo scenario. 
However, he can no longer edit the latest one and save it as another configuration.

The offending workflow is `config with all params added`:
https://app.staging.terarium.ai/projects/ad8a0f46-b598-4261-880d-5148bfc94f9a/workflow/21479066-d8bd-4f7f-b63d-7377d0b73ef9?operator=d62dcf29-2fec-46e8-9af5-5ed078be53c5

This happens also for the configurations named `Contact config with ...` and _some_ of the `Contact config`. It doesn't happen to those called `NL Test...`.

We get this error when we try to save this configuration with "Save as".
It appears regardless of whether we edit it or not.
![Screenshot 2024-09-04 at 5 38 30 PM](https://github.com/user-attachments/assets/5198623e-4032-4b78-ba56-13fb1ce6e367)

**Comment by mwdchang** [comment]
This is caused by a bad setter in ParameterSemantic Java class, but then had been subsequently changed in a different PR that resolved the issue. The version of Terarium you are testing with does that have the latter changes.


References:
- https://github.com/DARPA-ASKEM/terarium/pull/4481/files
- https://github.com/DARPA-ASKEM/terarium/pull/4667
