### ISSUE TITLE
[BUG]: workflow nodes get misconnected for no obvious reason

### ISSUE THREAD

**Issue by pascaleproulx** [DARPA-ASKEM/terarium#4828]
**Describe the bug**
I am working on a workflow. While in it, nodes start to appear misconnected (one end of a link missing the round ball). No idea why it is happening. 

https://app.staging.terarium.ai/projects/59d1af73-e373-42da-9e88-ac020a39cc1f/workflow/8dfacd1a-d997-4d22-86fc-c6ea8c3f5a6a

**Screenshots**
Only thing I can see as error in the console is this:
![image](https://github.com/user-attachments/assets/b6b27a02-30ba-40cf-b733-133af1180ab0)
![image](https://github.com/user-attachments/assets/1d633fd0-a7bd-4eb3-991f-52e05cf8e6c7)
![image](https://github.com/user-attachments/assets/d877879f-faa6-449d-a9f6-ea1a16a4ef93)

**Comment by mwdchang** [comment]
I am not sure how this bug is happening - I have yet to recreate.

One possible conjecture is that interaction are happening really fast, and a previous update partially overwrite the action to link the edge.

- Add model-operation
- Add model-config operation
- Move node around
- Add edge

The update from moving node interfere with add edge before the update is sent server side...
