### ISSUE TITLE
[BUG]: Simulate result AI summary not working

### ISSUE THREAD

**Issue by YohannParis** [DARPA-ASKEM/terarium#4850]
- Scenario: [Simulate](https://github.com/DARPA-ASKEM/terarium/blob/main/testing/manual/simulate.md
- Step: 3 Running simulation
- Link to the project: https://app.staging.terarium.ai/projects/8583471a-9f09-49c2-8501-cf239870ba58/workflow/ab7f641f-99c3-4489-8672-d834c7bde053?operator=e40abfe4-5131-4764-95ae-f0a9de682d4b

**Describe the issue**
The AI summary was not generated:

![Screenshot 2024-09-19 at 11 23 10](https://github.com/user-attachments/assets/c1721862-66e4-44b2-b0e4-8b214b56e60e)

**Comment by mwdchang** [comment]
There seems to be no issue here,  because the summarization relies on a generic summarization endpoint in gollm-taskrunner,  probably this, among many other things went awry with the bad taskrunner deployment.

However, the summarization should take into consideration of interventions, which currently it does not.
