### ISSUE TITLE
[FEAT]: Model diagram: Need better graph layout 

### ISSUE THREAD

**Issue by pascaleproulx** [DARPA-ASKEM/terarium#5006]
If the users tries to change the layout by moving nodes manually, the edges are not redrawn to follow shortest path between the nodes. There should also probably be a reset layout button.
![image](https://github.com/user-attachments/assets/d543ad25-4025-425b-bb65-090b4aaee53e)

**Comment by mwdchang** [comment]
Dagre (the algorithm/library we use) doesn't really have the notion of a stand-alone edge routing so this is something we need DIY.

Using AStar to route the edges works, but because it is a greedy-algorithm it has the tendency to route edges such that they take the same optimal path, which is mathematically sound but not pleasing to the viewer.

There are a couple of posts about grid-based, orthogonal edges that look like they can be leveraged here, as our model-diagrams are fairly simple nowadays (no longer any hierarchical structures or cross-hierarchy edges).

See:
- Demo: https://orthogonal.jose.page/
- https://medium.com/swlh/routing-orthogonal-diagram-connectors-in-javascript-191dc2c5ff70
- https://gist.github.com/jose-mdz/4a8894c152383b9d7a870c24a04447e4


Misc:
- https://gist.github.com/jose-mdz/ed70f7d5677f6b9df63ee904a6a33743
