### ISSUE TITLE
[BUG]: App crash when running Optimize intervention settings

### ISSUE THREAD

**Issue by mloppie** [DARPA-ASKEM/terarium#5195]
- Scenario: https://github.com/DARPA-ASKEM/terarium/blob/main/testing/manual/optimize.md
- Step: running Optimize intervention 
- Link to the project: https://app.staging.terarium.ai/projects/d0d0e082-8556-4906-ad84-cfb7d5be9afb/workflow/ec5c7b56-1bad-4c7d-b537-d2aa456733e9?operator=889186fb-b679-422f-89fe-1c338ec7ed72

**Describe the issue**
App crashes with array out of bounds error

![Image](https://github.com/user-attachments/assets/09f83c48-0e10-4307-b24e-882b03fe1a43)

**Comment by Tom-Szendrey** [comment]
For the record this is because we set end time for the intervention to be `150` and the optimize setting end time to `90` 
I will look to update the UI two ways
1) Do not allow the user to hit run when optimize end time < any intervention end time
2) highlight any infractions to this in red so it is easier for user to find infractions
