### ISSUE TITLE
[BUG]: Calibrated model configuration does not behave as expected

### ISSUE THREAD

**Issue by mwdchang** [DARPA-ASKEM/terarium#5784]
@liunelson and @hvasque14 report that calibrated model-config behaves differently in 
- calibrate operator
- simulate operator

In that it yields drastically different results, for example the infection curve of the "after-calibrate" in calibrate-operator looks very different than if we pipe the calibrate-operator's output into a simulate operator and simulate with the same time/sampling parameters we had used in calibarate.

**Comment by liunelson** [comment]
Here's a link to the workflow with the weird calibrate vs. simulate charts
https://app.staging.terarium.ai/projects/74cced0c-4d1c-4003-9cc5-69012dc3ab9c/workflow/77ac7570-bfc5-400a-b791-b3785a141c88

**Comment by blanchco** [comment]
I am getting the same curves now for both the calibrate and simulate nodes, I'm assuming due to @Tom-Szendrey 's fix [here](https://github.com/DARPA-ASKEM/terarium/pull/5877).

Running the calibration again it appears that the curves are the same, but I do not see any difference between the before and after calibration.  Im not sure if this is expected?? 

cc @liunelson

**Comment by blanchco** [comment]
I will be closing this as the results are now the same.  _If_ there is an issue with calibrate, this should be created in a separata ticket.
